exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar
exec-once = mako
exec-once = hyprpaper
exec-once = hyprctl setcursor Bibata-Modern-Classic 20
exec-once = gsettings set org.gnome.desktop.interface icon-theme "Nordzy-dark"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Nordic"

windowrulev2 = opacity 1.0 override 1.0 override, class:^(firefox)$
input {
	kb_layout = us
	sensitivity = 0.1
	accel_profile = flat
	scroll_factor = 0.1
	kb_options = caps:escape,altwin:swap_alt_wi
	kb_variant =
	kb_model =
	kb_rules =
	follow_mouse = 1
	repeat_rate = 25
	repeat_delay = 600
	numlock_by_default = true
}
general {
	gaps_in = 2
	gaps_out = 2
	border_size = 3
	resize_on_border = true
}
decoration {
	rounding = 10
	active_opacity = 0.8
	inactive_opacity = 0.7

}
debug {
	disable_logs = false
}

bind = SUPER, return, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, M, exit
bind = SUPER, B, exec, firefox
bind = SUPER, C, exec, kitty --hold sudo nano ~/.config/hypr/hyprland.conf
bind = SUPER, E, exec, thunar
bind = SUPER, F, fullscreen
bind = SUPER, V, togglefloating
bind = SUPER, S, exec, wofi --show drun -n
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
# Volume & Mic
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Brightness
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-
bind = , XF86MonBrightnessUp, exec, brightnessctl set 10%+

# Keyboard Backlight (if available)
bind = , XF86KbdBrightnessDown, exec, brightnessctl -d *::kbd_backlight set 10%-
bind = , XF86KbdBrightnessUp, exec, brightnessctl -d *::kbd_backlight set 10%+
