monitor=DP-3,2560x1440@144,0x0,1 
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar
exec-once = mako
exec-once = hyprpaper
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Nordic"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "Nordzy-yellow-dark"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = wal -R
exec-once = ~/.config/hypr/update_hypr_colors.sh
windowrulev2 = opacity 0.8 0.8, class:^(Thunar)$
windowrulev2 = opacity 0.8 0.8, class:^(kitty)$
env = HYPRCURSOR_THEME, Bibata-Modern-Classic
env = HYPRCURSOR_SIZE, 24
input {
	kb_layout = us
	sensitivity = 0.2
	accel_profile = flat
	scroll_factor = 1.5
}
general {

     	gaps_in = 5
	gaps_out = 5
	border_size = 3
	resize_on_border = true
}
decoration {
	rounding = 10


}
debug {
	disable_logs = false
}

bind = SUPER, return, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, M, exit
bind = SUPER, B, exec, firefox
bind = SUPER, C, exec, kitty --hold sudo nano ~/.config/hypr/hyprland.conf
bind = SUPER, E, exec, thunar
bind = SUPER, F, fullscreen
bind = SUPER, V, togglefloating
bind = SUPER, S, exec, wofi --show drun --style ~/.config/wofi/style.css --conf ~/.config/wofi/config
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, L, exec, kitty systemctl suspend
